### ISSUE TITLE
add support for Leiningen's dependency scopes

### ISSUE THREAD

**Issue by esuomi** [borkdude/lein2deps#1]
Hi,

As far as I can tell, this tool doesn't support Leiningen's dependency scopes, eg.
```clojure
[xxx "1.0.0" :scope "provided"]
```
As per discussion at [ClojureVerse](https://clojureverse.org/t/how-to-provide-a-dependency-scope-in-tools-deps/1862) this could/should be done by converting these scopes to aliases with extra-deps/override-deps.

**Comment by borkdude** [comment]
PR welcome to add those to an alias, e.g. `:dev` maybe?

**Comment by borkdude** [comment]
Already fixed
