### ISSUE TITLE
Add repositories from project.clj to deps.edn

### ISSUE THREAD

**Issue by dakra** [borkdude/lein2deps#4]
I'm not really familiar with leinigen so not sure if :mvn/repos in deps.edn is the same as :repositories in project.clj.

E.g. the `:repositories` key like [here](https://github.com/fundingcircle/jackdaw/blob/bac4feb06b068757ab5f14dd65bb26b3ac89408a/project.clj#L8) could then end up in `deps.edn` like:

`:mvn/repos {"confluent" {:url "https://packages.confluent.io/maven/"}}` ?

**Comment by borkdude** [comment]
Seems like a good thing to add, PR welcome
