### ISSUE TITLE
Maintain order of original deps

### ISSUE THREAD

**Issue by jeroenvandijk** [borkdude/lein2deps#7]
I saw in a project that the deps order is shuffled ([deps.edn](https://github.com/clj-commons/aleph/blob/a282af98817a89cba109b420ea5c8ae8b44ff0d6/deps.edn) vs [project.clj](https://github.com/clj-commons/aleph/blob/master/project.clj#L10)). Do you agree it make sense to maintain the order? 

I understand the generated `deps.edn` file is a compile artifact and should not be used as reference, but it is nice if you open it and the order somewhat makes sense. Also better if you want to migrate from `lein` to `deps.edn` at some point. Another argument would be smaller git diffs.

I think introducing an ordered hash-map instead of a normal hash-map should fix this, but I can experiment with this if you agree you want this change.

**Comment by borkdude** [comment]
This library is used by people in babashka, so we have to ensure that it keeps running that way.

We could use flatland.ordered which is available in babashka.

```
$ bb -e '(flatland.ordered.map/ordered-map {:a 1})'
#ordered/map ([:a 1])
```

Another approach could be to use rewrite-edn:

https://github.com/borkdude/rewrite-edn

and insert the key-values in the original order.

**Comment by jeroenvandijk** [comment]
A good to know. I'll try with `flatland.ordered.map` first. 

I can imagine the rewrite-edn option is especially useful if at some point you want to prevent the maps to change in the `#mvn{:version ...}` form and keep a normal map.

**Comment by borkdude** [comment]
We can prevent that using `(binding [*print-namespace-maps* false] ...)` if we're not already doing that.
